FROM node:14.5.0-buster

USER root
RUN npm install -g typescript mocha ts-node

ENV USER_ID=1300
RUN usermod -u $USER_ID node

WORKDIR /home/node/cypherpost/app


COPY --chown=node:node package*.json ./
RUN npm install
COPY --chown=node:node . .
RUN tsc

USER node
RUN mkdir -p /home/node/cypherpost/app
RUN mkdir -p /home/node/winston && mkdir /home/node/.keys

USER node

ENV MOLTRES_PORT="3021"
ENV DB_IP="database"
ENV DB_PORT="27017"
ENV DB_NAME="cypherpost"
ENV DB_AUTH="___DBAUTH___"
ENV KEY_PATH="/home/node/.keys/"
ENV SERVER_PUBKEY = "ceaf836b3d29dfd686be0a02e3c36ca7f00bc5ed013f92cd176989424eb82574";
ENV SERVER_NAME = "CYPHERPOST MAIN";
#------------------------------------------------------------------------------------
#------------------------------------------------------------------------------------
VOLUME ["/home/node/.keys","/home/node/winston"]
EXPOSE $APP_PORT
CMD ["npm", "start"]
#------------------------------------------------------------------------------------
